### PR TITLE
updates to ants mapping

### PR DESCRIPTION
**Pull request by satra**

### CODE REVIEW

**Comment by satra** [comment]
@dbkeator - a ping here as well.

**Comment by dbkeator** [comment]
@satra FYI, it appears the model is working with respect to alerting us that there is a missing region.  I got the following key error from my conversions.  I don't think this should be a blocker for simple 2...

Key ANTSDKT(structure='5th-Ventricle', hemi=None, measure='VolumeInVoxels', unit='voxel') not found in ANTS data elements file

**Comment by satra** [comment]
@dbkeator - i'll take a look at this a little later. shouldn't be the case.

can you point me to the url of the file that gave you this error?

**Comment by satra** [comment]
@dbkeator  - just checked with a file i have and that didn't generate an error.

can you share with me the three files you used?

```
In [1]: from ants_seg_to_nidm.antsutils import read_ants_stats, ANTSDKT, hemiless
   ...: , create_ants_mapper, create_cde_graph, convert_stats_to_nidm            
RDFLib Version: 5.0.0

In [2]: m = read_ants_stats('antslabelstats.csv', 'antsbrainvols.csv', 'antsExtractedBrain0N4.nii.gz', force_error=True)                                  
```

**Comment by dbkeator** [comment]
@satra My scripts aren't outputting the participant ID for these errors so I can't be sure which ID is applies to.  I'd like to let the scripts finish and I'll go back and see if I can track down which ID resulted in the error.

The URLs I'm using:

https://fcp-indi.s3.amazonaws.com/data/Projects/ABIDE/Outputs/mindboggle_swf/mindboggle/ants_subjects/sub-[ID]/antslabelstats.csv
https://fcp-indi.s3.amazonaws.com/data/Projects/ABIDE/Outputs/mindboggle_swf/mindboggle/ants_subjects/sub-[ID]/antsbrainvols.csv
https://fcp-indi.s3.amazonaws.com/data/Projects/ABIDE/Outputs/mindboggle_swf/mindboggle/ants_subjects/sub-[ID]/antsBrainSegmentation.nii.gz

**Pull request merged**
